### ISSUE TITLE
插件的class_regex和window_regex似乎反了

### ISSUE THREAD

**Issue by mxia9416** [neko-para/maa-support-extension#3]
在桌面端开发时发现插件的class_regex和window_regex两个参数似乎对应反了，如图想捕捉《白荆回廊》的窗口时必须写成如下才能被插件识别
![image](https://github.com/user-attachments/assets/8aecbbdf-e019-4d69-b45e-a66ca52dfbc5)
![image](https://github.com/user-attachments/assets/7383e8f3-e702-477c-9826-154573322029)
但这会导致MaaPiCli无法正确识别窗口
![image](https://github.com/user-attachments/assets/4ffd4923-0b8b-4fe5-8cac-4e11cbad61d5)
根据参数名字定义应该是插件接反了？

**Comment by mxia9416** [comment]
尝试将插件回滚到1.x版本后，发现window_regex写窗口标题是对的，所以应该确实是升级2.x的时候接反了~

**Comment by neko-para** [comment]
@mxia9416 修好了，可以先用CI的包，在vscode里面`从VSIX安装`就行
https://github.com/neko-para/maa-support-extension/actions/runs/12335804858
